### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by vvyomjjain** [ykdojo/editdojo#1]
Hey @ykdojo,

This sounds like a really cool project judging by the idea described in the video. But the repo doesn't have a readme to give a description. I know the repo doesn't have much to describe as of now, I'll still suggest adding one.

**Comment by ykdojo** [comment]
Okay, good idea. If you don't mind, it would be great if you could send me a pull request for that, too :)

(I think you should be able to send it but I'm not 100% sure since I'm not that used to using GitHub.)

**Comment by vvyomjjain** [comment]
Okay on it. Don't worry about the GitHub thing. I'll help you out, that's what GitHub is all about. And since you capitalized 'H', you're already getting there. 😂

**Comment by ykdojo** [comment]
Lol thanks!!
