### ISSUE TITLE
Make a TODO app with Django

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/editdojo#15]
I'm actually still in the process of learning Django basics.

I realized I should probably build a simple app like a TODO app first. It will be a prerequisite for building the *log in with Twitter* function, I think. (Since we'll need to store user data in our database)

So, maybe this will be my next video, instead.

**Comment by ykdojo** [comment]
My current plan: I'm going to follow the *polls* tutorial on Django's official website first to get a better grasp of the technology.
https://docs.djangoproject.com/en/2.1/intro/tutorial01/

**Comment by malek2610** [comment]
Thanks for sharing

**Comment by Barsnes** [comment]
Will you be covering how we could store our data in an online database aswell?
