### ISSUE TITLE
How about accounts?

### ISSUE THREAD

**Issue by HallBregg** [ykdojo/editdojo#19]
Maby we should start thinking about creating views and models for users accounts?

**Comment by ykdojo** [comment]
Yes, I think we should. I was thinking of doing it when I do the log in
with Twitter function

**Comment by HallBregg** [comment]
Maby I could do some mock-up of it?

**Comment by ykdojo** [comment]
Sure! That’ll be great!

**Comment by malek2610** [comment]
@HallBregg What do you use to make mock-ups please?

**Comment by malek2610** [comment]
@HallBregg I was just asking about the software you're going to use. Actually, I know about [Balsamiq](https://balsamiq.com/) ; it's a commercial software. But I am not sure if it exists an equivalent or other softwares which are used.

**Comment by HallBregg** [comment]
Yeah, I understood. Maby I should use word "mock up" . All I meant was to make fully working login, and registration (accounts) views and models in Django. I am more backend developer. Dont know much about style and how should it look visually.

**Comment by malek2610** [comment]
@HallBregg Oh I see, thanks for your reply.

**Comment by codepiri** [comment]
@HallBregg 

http://pencil.evolus.vn
Pencil is built for the purpose of providing **a free and open-source GUI prototyping** tool that people can easily install and use to create mockups in popular desktop platforms.

**Comment by malek2610** [comment]
@HallBregg thanks so much. I'm wondering if it exists an online similar tool (open-source free will be great !)

**Comment by alpharomeo7** [comment]
Should there be a username or is email find? 
There are pros and cons of Usernames so it is important to think about.

If you decide not to use Username, you would have to use Cumstom User model for Django users.

**Comment by ykdojo** [comment]
Okay I'll think about this when I work on #11.

Closing this issue for now.
