### ISSUE TITLE
Find the difference between two sets of text with JavaScript

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/editdojo#22]
Example:

- Original text: I had aweesome breakfast tooday.
- Edited text: I had awesome breakfast today.

Given these two sets of text, we should be able to find the difference with JavaScript. And show the difference in UI. This way, it'll be easy to see how the original text has been edited.

In this case, it should look like this: I had awe\<e\>some breakfast to\<o\>day.

(Where \<e\> and \<o\> have strikethrough over them)

**Comment by haruntuncay** [comment]
Hi @ykdojo . Can I be assigned to this please ?
And, I think, added characters in the edited text should also be highlighted with maybe something like greenish background color.

    Original text: I had aweesome breakfast tooday.
    Edited text: I had an awesome breakfast today.

So it may give an output like this:

`<p>I had <span class="appended">an</span> awe<span class="deleted">e</span>some breakfast to<span class="splitted">o</span>day.`

Where the appended words/chars are wrapped in a span with class .appended, and deleted words/chars are wrapped in a  span with class .deleted.

**Comment by ykdojo** [comment]
That sounds perfect! I'll assign this to you :)

**Comment by ykdojo** [comment]
Found this library, but not sure if it would be a good fit for this: https://github.com/jhchen/fast-diff

**Comment by ykdojo** [comment]
Maybe it would be better/simpler to just implement this ourselves? That way, it'll be easier to tweak it as we go, too. I just don't like how most of these libraries are really complex to read and edit... Anyway, I'll think about this some more.

**Comment by ykdojo** [comment]
Started working on this today.

Pretty raw and it might be hard to read, but I have some code here already: https://github.com/ykdojo/text_difference_finder

**Comment by JustaFrank** [comment]
Hey @ykdojo did you look at my pull request ([(24](https://github.com/ykdojo/editdojo/pull/25)])?

**Comment by ykdojo** [comment]
@JustaFrank hey sorry I thought I'd submitted my comments already. I just sent them again.

**Comment by ykdojo** [comment]
I was thinking of implementing something on my own and comparing it to yours.

**Comment by ykdojo** [comment]
Here are some examples for testing, in English:
- Hello I’m looking of the group for learn english.
-> Hello, I’m looking for a group to learn English with.

- what book are you reading ? i want to start this one… what do you think about ?
-> What book are you reading? I want to start this one… What do you think about it?

- who helps me for improving my English?
-> Can anyone help me improve my English?

- I am waiting for snow from this morning until now.
-> I’ve been waiting for snow since this morning.

- even I have French nationality. I still make mistake when I write my own sentences .
-> Even though I’m French, I still make mistakes when I write in French.

**Comment by ykdojo** [comment]
And some test cases in Japanese:
- 日本語でも英語でもドラマよく見ている。
-> 日本語でも英語でもドラマをよく見ています。
- きのうのばんごはんはとてもおいしかたです。
-> きのうのばんごはんはとてもおいしかったです。
- わたしのしごとのま、わたいはそうだいなけしきをみました
-> しごとのあいまにきれいなけしきをみました。
- 知らない人とお喋りのが怖いです。
-> 知らない人とお喋りするのが怖いです。
- Duolingoは本とに凄いアプリです。
-> Duolingoは本当に凄いアプリです。
- 今朝はとても寒い！冬ははやく来る。
-> 今朝はとても寒いですね！冬がもうすぐ来そうです。

**Comment by JustaFrank** [comment]
I changed a few lines of code, which split the strings by character. Having the option to split by words or character should be enough to cover most languages, I think.
<img width="438" alt="textdif" src="https://user-images.githubusercontent.com/31837071/48591705-ddc55d00-e8f9-11e8-954b-cc9dd1268fcb.PNG">
Should I submit another pull request?

**Comment by ykdojo** [comment]
Sure, that sounds perfect.

I made my own version [here](https://github.com/ykdojo/text_difference_finder), so I might pick yours or mine, or try merge them later on.

So one of the reasons I wanted to make my own version is because I wanted to learn how it works myself, and another reason is just because I wanted to make a video about it.

Anyway, I think it's good to have multiple solutions available to choose from :)

**Comment by ykdojo** [comment]
Solved this in my last video. I'll close this issue for now. https://youtu.be/4SP_AY7GGxw

**Comment by ykdojo** [comment]
Also thanks for your code, @JustaFrank. I got a lot of inspiration from your code for that video.
