### ISSUE TITLE
Change the database management system

### ISSUE THREAD

**Issue by glxnull** [ykdojo/editdojo#6]
Which database manager do you consider the best option to use in the project?

**Comment by ykdojo** [comment]
No idea yet-- will need to figure out!

**Comment by SindhuVempati** [comment]
PostgreSQL might suit better.

**Comment by didoloan** [comment]
POSTGRESQL works well with Django.

**Comment by ykdojo** [comment]
Okay cool. Why not MySQL or anything else like that though?

**Comment by didoloan** [comment]
MySQL would be good too.

**Comment by didoloan** [comment]
It's just that postgresql has a deeper feature set similar to closed source RDBMS.

**Comment by ykdojo** [comment]
Okay maybe we'll go with postgresql then. I don't have a strong preference on this though.

**Comment by Anu1601CS** [comment]
@ykdojo yes PostgreSQL is better with Django project.

**Comment by glxnull** [comment]
A lot of projects begin using MySQL and then according as the app gets bigger they switch to another DB manager.

**Comment by 5Volts** [comment]
By the way, who's will work on the front end?

**Comment by ykdojo** [comment]
I'm planning to work on it, plus whoever wants to work on it.

**Comment by didoloan** [comment]
Have u decided on the front-end framework to use.

**Comment by didoloan** [comment]
I would love to work with u on that.

**Comment by ykdojo** [comment]
Yeah I think I'm going to use plain HTML/CSS/JS at the beginning, and then
maybe React later.

**Comment by didoloan** [comment]
Cool

**Comment by cathaldcronin1** [comment]
@ykdojo You could use Vue, I currently, use it in work and it's very straightforward and quick to get up and running
